repo: https://github.com/madler/zlib.git
ver: v1.2.11
tag_prefix: 
tag_dot2ul: false
cb_tool: cmake
config_options_1: -DBUILD_SHARED_LIBS=OFF
config_options_2: ''
config_options_msw: -DBUILD_SHARED_LIBS=ON
