repo: https://github.com/curl/curl.git
ver: 7.78.0
tag_prefix: 'curl-'
tag_dot2ul: true
cb_tool: cmake
config_options_1: -DCMAKE_USE_LIBSSH2=FALSE -DBUILD_CURL_EXE=FALSE -DCURL_DISABLE_TESTS=TRUE -DCMAKE_USE_OPENSSL=TRUE
config_options_2: ''
config_options_msw: -DCMAKE_USE_LIBSSH2=FALSE -DBUILD_CURL_EXE=FALSE -DCURL_DISABLE_TESTS=TRUE -DCMAKE_USE_OPENSSL=TRUE -DBUILD_SHARED_LIBS=ON
cmake_target: libcurl
