repo: https://www.openssl.org/source/openssl-3.0.1.tar.gz
ver: 3.0.1
tag_prefix: openssl-
tag_dot2ul: false
cb_tool: perl
config_options_unix: no-tests no-comp no-shared
config_options_embed: 
config_options_msw: no-tests no-comp
