# This is a basic workflow that is manually triggered

name: test-ci

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Distribute openssl prebuilt lib?'
        # Default value if no value is explicitly provided
        default: 'yes'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: mkdir -p dist

    - run: echo hello > dist/world.txt

    - uses: actions/upload-artifact@master
      with:
        name: hello-world-artifact
        path: dist/world.txt

  job2:
    runs-on: macos-latest

    steps:
    - run: mkdir -p dist

    - uses: actions/download-artifact@master
      with:
        name: hello-world-artifact
        path: dist/world.txt

    - run: cat dist/world.txt
  # This workflow contains a single job called "greet"
  dist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Test input
      run: echo "Hello ${{ github.event.inputs.name }}"
      
    - name: Test downloaded files
      run: |
        gh version
        # gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
        # gh run download
        ls -R
