name: windows-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - .github/workflows/windows-ci.yml
      - 1k/build.ps1
      - build.properties
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1.9.0
        with:
          arch: ${{ matrix.arch }}

      - name: Build openssl
        run: .\1k\build.ps1

      - name: Upload openssl prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./openssl/${{ env.INSTALL_NAME }}/**/*
          name: ${{ env.INSTALL_NAME }}
